keys:
  - &admin_greysilly7 age1f0yw5e9w55r5zwun8nfqzezpze6gsez4lkyw44z26efc87na8dhq56yztk
  - &computer_laptop age1g0guhy2s5p5rqfgs4md93kf5lpeak9afyxa2kk3y6uwquaj9xfwsdnhh3a
  - &computer_server age1dlkt44dm4t5q9uqvnc3yf7aw6zy7cnaczm0ex5rgaatxfxtj2p9q6knnyr
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_greysilly7
          - *computer_laptop
          - *computer_server
