keys:
  - &admin_greysilly7 age1f0yw5e9w55r5zwun8nfqzezpze6gsez4lkyw44z26efc87na8dhq56yztk
  - &gaminglaptop age1wj30wew0p07p0af8fkenvyr4vrc0lf7ps4x8qehvnvykle8c493sjtttz7
  - &server_dellpoweredge age1xgezes2cpmzzmd986hhr7vh4z7avzd6nwcxryjf2efwzrya6r9qqq6k4yg
  - &server_desktopserver age1kwa8ke9z8g9u9arwe4je46pmkdncq3hdryq406jj00x2p7hr59sqz3cza6
  - &server_fastbar age14ue4m33pcp5pvgt79axulashdq3dywuydzwast3hqwtcstss258s4qrkeq

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_greysilly7
          - *gaminglaptop
          - *server_dellpoweredge
          - *server_desktopserver
          - *server_fastbar
