# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  pkgs,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    ./disks
  ];

  boot.extraModprobeConfig = ''
    options snd_hda_intel power_save=1
    options iwlmvm power_scheme=3
  '';

  boot.initrd.systemd.enable = true;
  boot.initrd.systemd.tpm2.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  hardware.laptop.enable = true;

  facter.reportPath = ./facter.json;

  hardware.graphics = {
    enable = true;
    extraPackages = lib.attrValues {
      inherit
        (pkgs)
        vaapiIntel
        libva
        libvdpau-va-gl
        vaapiVdpau
        ocl-icd
        intel-compute-runtime
        ;
    };
  };
}
